# -*- coding: utf-8 -*-

import os,base64,sys,urllib2,urlparse,xbmc,xbmcaddon,xbmcgui
from resources.lib.modules import control,cache,trakt

sysaddon = sys.argv[0] ; syshandle = int(sys.argv[1]) ; control.moderator()
artPath = control.artPath() ; addonFanart = control.addonFanart()
imdbCredentials = False if control.setting('imdb.user') == '' else True
traktCredentials = trakt.getTraktCredentialsInfo()
traktIndicators = trakt.getTraktIndicatorsInfo()
queueMenu = control.lang(32065).encode('utf-8')


class navigator:
    def root(self):
        self.addDirectoryItem('Hulu Originals', 'tvshows2&url=tmdbhuluorig', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Netflix Originals', 'tvshows2&url=tmdbnetflixorig', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Amazon Originals', 'tvshows2&url=tmdbamazonorig', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Top 250 TV Shows', 'tvshows2&url=tmdbjew250tv', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('YouTube Red Tv Shows', 'movies2&url=tmdbjewmovies', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Super DC/Marvel', 'mysupermvNavigator', 'userlists.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Holiday Lists', 'myholidmvNavigator', 'userlists.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Classics Lists', 'myclassicsNavigator', 'userlists.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('TV Show Lists', 'myurantvNavigator', 'userlists.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Movie Lists', 'myuranmvNavigator', 'userlists.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('More Movie Lists', 'mymoreNavigator', 'userlists.png', 'DefaultVideoPlaylists.png')
        self.endDirectory()


    def myuranmv(self, lite=False):
        self.addDirectoryItem('80s Movies', 'movies2&url=tmdbsnatched', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('90s Movies', 'movies2&url=tmdbsports', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('420', 'movies2&url=tmdb420', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Best Picture Winners', 'movies2&url=tmdbbestpicwin', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Boxsets Movies', 'movies2&url=tmdbboxsetmovies', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('ChickFlicks', 'movies2&url=tmdbdatenight', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Cold War', 'movies2&url=tmdbcold', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Comedy', 'movies2&url=tmdbcomed', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Cons', 'movies2&url=tmdbconman', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Conspiracy', 'movies2&url=tmdbconsp', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Court', 'movies2&url=tmdbgamers', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Disney', 'movies2&url=tmdbdisney', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Disney Movies', 'movies2&url=tmdbdisnemovies', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Dreamworks', 'movies2&url=tmdbdreamworks', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Drug-Related', 'movies2&url=tmdbdrugrel', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('FBI', 'movies2&url=tmdbanimal', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Fighting', 'movies2&url=tmdbfight', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Gangster', 'movies2&url=tmdbgangsters', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Hackers', 'movies2&url=tmdbhack', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Heist', 'movies2&url=tmdbheist', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Kids Collection', 'movies2&url=tmdbkidz', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Lego Collection', 'movies2&url=tmdblego', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Mafia Hits', 'movies2&url=tmdbmafia', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Man and Machine', 'movies2&url=tmdburban', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Oscars', 'movies2&url=tmdboscars', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Politics', 'movies2&url=tmdbchi', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Princesses', 'movies2&url=tmdbprincess', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('SciFi', 'movies2&url=tmdbufo', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Scottish', 'movies2&url=tmdbgwg', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Skateboarding', 'movies2&url=tmdbbooks', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Spies', 'movies2&url=tmdbspy', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Spotlight', 'movies2&url=tmdbspotlight', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Stand Up', 'movies2&url=tmdbstandup', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Star Trek', 'movies2&url=tmdbvigilante', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Cars the Star', 'movies2&url=tmdbfast', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('True Stories', 'movies2&url=tmdbtruestory', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('True Story', 'movies2&url=tmdbbased', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('War', 'movies2&url=tmdbtragedy', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.endDirectory()
        
        
    def myholidmv(self, lite=False):
        self.addDirectoryItem('4th of July', 'movies2&url=tmdbfourth', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Christmas', 'movies2&url=tmdbchristmas', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Easter', 'movies2&url=tmdbeaster', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Halloween', 'movies2&url=tmdbhalloween', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('New Years', 'movies2&url=tmdbnewyear', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Thanksgiving', 'movies2&url=tmdbthanks', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Valentines Day', 'movies2&url=tmdbvalentines', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Xmas', 'movies2&url=tmdbxmas', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.endDirectory()
        
        
    def mysupermv(self, lite=False):
        self.addDirectoryItem('DC Movies', 'movies2&url=tmdbdcmovies', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('DC Animated Movies', 'movies2&url=tmdbdcanimovies', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The DC Movies', 'movies2&url=tmdbdc', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Marvel Movies', 'movies2&url=tmdbmarvelmovies', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Marvel Animated Movies', 'movies2&url=tmdbmarvelanimovies', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Marvel Movies', 'movies2&url=tmdbmarvel', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Super Heroes', 'movies2&url=tmdbhero', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.endDirectory()
        
        
    def myurantv(self, lite=False):
        self.addDirectoryItem('Adult Animation', 'tvshows2&url=tmdbsouthptv', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Animation', 'tvshows2&url=tmdbanimationtv', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Cartoons Blast From The Past', 'tvshows2&url=tmdbcartoon', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('CIA', 'tvshows2&url=tmdbgamers', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Classic', 'tvshows2&url=tmdbblast', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Comedy', 'tvshows2&url=tmdblmao', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Court', 'tvshows2&url=tmdbchitv', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Datenight', 'tvshows2&url=tmdbdatenighttv', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Elimination', 'tvshows2&url=tmdbelimination', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('FBI', 'tvshows2&url=tmdbcooking', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Kids-TeleVision', 'tvshows2&url=tmdbkids', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Man and Machine', 'tvshows2&url=tmdbsportstv', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Organised Crime', 'tvshows2&url=tmdbtats', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Out Of This World', 'tvshows2&url=tmdbufotv', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('PreSchool', 'tvshows2&url=tmdblittle', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Spotlight', 'tvshows2&url=tmdbspotlighttv', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Cars the Star', 'tvshows2&url=tmdbfasttv', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('True Story', 'tvshows2&url=tmdb420tv', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.endDirectory()
        
        
    def boxes(self, lite=False):
        self.addDirectoryItem('3 Ninjas', 'movies2&url=tmdb3nin', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('12 Rounds', 'movies2&url=tmdbrounds', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('28 Days Later', 'movies2&url=tmdb28days', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('101 Dalmations', 'movies2&url=tmdbdal', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('300', 'movies2&url=tmdb300', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('A Goofy Movie', 'movies2&url=tmdbgoofy', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('A Haunted House', 'movies2&url=tmdbhaunted', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('A Nightmare on Elm Street', 'movies2&url=tmdbelmst', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Ace Ventura', 'movies2&url=tmdbace', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Adams Family', 'movies2&url=tmdbadams', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Agent Cody Banks', 'movies2&url=tmdbagent', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Aladdin', 'movies2&url=tmdbaladdin', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Alice In Wonderland', 'movies2&url=tmdbalice', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Alien', 'movies2&url=tmdbalien', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('All Dogs Go to Heaven', 'movies2&url=tmdballdogs', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('American Ninja', 'movies2&url=tmdbamninja', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('American Pie', 'movies2&url=tmdbampie', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Anchorman', 'movies2&url=tmdbanchor', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Austin Powers', 'movies2&url=tmdbaustin', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Avengers', 'movies2&url=tmdbavengers', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('AVP', 'movies2&url=tmdbavp', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Babe', 'movies2&url=tmdbbabe', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Back To The Future', 'movies2&url=tmdbback', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Bad Ass', 'movies2&url=tmdbbadass', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Bad Boys', 'movies2&url=tmdbbb', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Bad Neighbors', 'movies2&url=tmdbbn', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Balto', 'movies2&url=tmdbbalto', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Bambi', 'movies2&url=tmdbbambi', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Barbershop', 'movies2&url=tmdbbarber', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Batman', 'movies2&url=tmdbbatman', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Bean', 'movies2&url=tmdbbean', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Beauty and The Beast', 'movies2&url=tmdbbeauty', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Beethoven', 'movies2&url=tmdbbeethoven', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Best Of The Best', 'movies2&url=tmdbbob', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Beverly Hills Cop', 'movies2&url=tmdbbeverly', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Big Mommas House', 'movies2&url=tmdbbig', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Bloodsport', 'movies2&url=tmdbblood', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Blues Brother', 'movies2&url=tmdbblues', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Boondock Saints', 'movies2&url=tmdbboon', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Bourne', 'movies2&url=tmdbbourne', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Bridget Jones', 'movies2&url=tmdbbridget', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Brother Bear', 'movies2&url=tmdbbrotherbear', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Bruce Lee', 'movies2&url=tmdbbrucelee', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Captain America', 'movies2&url=tmdbcaptain', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Cars', 'movies2&url=tmdbcars', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Casper', 'movies2&url=tmdbcasper', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Cats & Dogs', 'movies2&url=tmdbcatsanddogs', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Charlottes Web', 'movies2&url=tmdbcharlottes', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Childs Play', 'movies2&url=tmdbchilds', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Cinderella', 'movies2&url=tmdbcinderella', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('City Slickers', 'movies2&url=tmdbcity', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Clerks', 'movies2&url=tmdbclerks', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Cloudy With A Chance of Meatballs', 'movies2&url=tmdbcloudy', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Cocoon', 'movies2&url=tmdbcocoon', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Conan', 'movies2&url=tmdbconan', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Crank', 'movies2&url=tmdbcrank', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Crocodile Dundee', 'movies2&url=tmdbcroc', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Crouching Tiger', 'movies2&url=tmdbcrouching', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Cube', 'movies2&url=tmdbcube', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Curious George', 'movies2&url=tmdbcurious', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Daddy Daycare', 'movies2&url=tmdbdaddy', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Despicable Me', 'movies2&url=tmdbdespicable', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Diary of A Wimpy Kid', 'movies2&url=tmdbdiary', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Die Hard', 'movies2&url=tmdbdie', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Dirty Dancing', 'movies2&url=tmdbdirtyd', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Dirty Harry', 'movies2&url=tmdbdirtyh', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Divergent', 'movies2&url=tmdbdivergent', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Doctor Dolittle', 'movies2&url=tmdbdolittle', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Dolphin Tale', 'movies2&url=tmdbdolphin', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Dragon Tattoo', 'movies2&url=tmdbdragon', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Dumb and Dumber', 'movies2&url=tmdbdumb', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Evil Dead', 'movies2&url=tmdbevil', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Exorcist', 'movies2&url=tmdbexorcist', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Fantasia', 'movies2&url=tmdbfantasia', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Fast and Furious', 'movies2&url=tmdbfurious', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('FernGully', 'movies2&url=tmdbferngully', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Final Destination', 'movies2&url=tmdbfinal', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Finding Nemo', 'movies2&url=tmdbfinding', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Fox and The Hound', 'movies2&url=tmdbfox', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Free Willy', 'movies2&url=tmdbfree', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Friday The 13th', 'movies2&url=tmdbfriday13', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Friday', 'movies2&url=tmdbfriday', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('G.I. Joe', 'movies2&url=tmdbgi', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Garfield', 'movies2&url=tmdbgarfield', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Ghost Rider', 'movies2&url=tmdbghost', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Ghostbusters', 'movies2&url=tmdbghostbusters', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Green Street Hooligans', 'movies2&url=tmdbgreen', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Gremlins', 'movies2&url=tmdbgremlins', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Grown Ups', 'movies2&url=tmdbgrown', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Grumpy Old Men', 'movies2&url=tmdbgrumpy', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Halloween', 'movies2&url=tmdbhalloween', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Hannibal Lecter', 'movies2&url=tmdbhannibal', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Happy Feet', 'movies2&url=tmdbhappy', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Harold and Kumar', 'movies2&url=tmdbharold', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Harry Potter', 'movies2&url=tmdbharry', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Hellraiser', 'movies2&url=tmdbhell', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Herbie', 'movies2&url=tmdbherbie', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Highlander', 'movies2&url=tmdbhighlander', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Hollow Man', 'movies2&url=tmdbhollow', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Home Alone', 'movies2&url=tmdbhome', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Homeward Bound', 'movies2&url=tmdbhomeward', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Honey I Shrunk The Kids', 'movies2&url=tmdbhoney', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Hoodwinked!', 'movies2&url=tmdbhoodwink', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Horrible Bosses', 'movies2&url=tmdbhorrible', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Hostel', 'movies2&url=tmdbhostel', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Hot Shots', 'movies2&url=tmdbhot', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Hot Tub Time Machine', 'movies2&url=tmdbhotub', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Hotel Transylvania', 'movies2&url=tmdbhotel', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('How To Train Your Dragon', 'movies2&url=tmdbhow', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Hunchback of Notre Dame', 'movies2&url=tmdbhunch', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Hunger Games', 'movies2&url=tmdbhunger', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Ice Age', 'movies2&url=tmdbiceage', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Independence Day', 'movies2&url=tmdbindependence', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Indiana Jones', 'movies2&url=tmdbindiana', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Infernal Affairs', 'movies2&url=tmdbinfernal', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Insidious', 'movies2&url=tmdbinsidious', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Inspector Gadget', 'movies2&url=tmdbinspector', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Ip Man', 'movies2&url=tmdbipman', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Iron Fists', 'movies2&url=tmdbironfists', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Jackass', 'movies2&url=tmdbjackass', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('James Bond', 'movies2&url=tmdbjames', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Jaws', 'movies2&url=tmdbjaws', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Johnny English', 'movies2&url=tmdbjohnny', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Journey', 'movies2&url=tmdbjourney', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Judge Dredd', 'movies2&url=tmdbdredd', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Jump Street', 'movies2&url=tmdbjump', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Jurassic Park', 'movies2&url=tmdbjurassic', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Justice League', 'movies2&url=tmdbjusticeleague', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Kick-Ass', 'movies2&url=tmdbkick', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Kickboxer', 'movies2&url=tmdbkickboxer', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Kill Bill', 'movies2&url=tmdbkill', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Kung Fu Panda', 'movies2&url=tmdbkung', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Lady and The Tramp', 'movies2&url=tmdblady', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Last Summer', 'movies2&url=tmdblast', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Legally Blonde', 'movies2&url=tmdblegally', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Lego Star Wars', 'movies2&url=tmdblegostar', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Lethal Weapon', 'movies2&url=tmdblethal', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Like Mike', 'movies2&url=tmdblikemike', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Lilo & Stitch', 'movies2&url=tmdblilo', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Look Whos Talking', 'movies2&url=tmdblookwho', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Lord of The Rings', 'movies2&url=tmdblord', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Machete', 'movies2&url=tmdbmachete', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Mad Max', 'movies2&url=tmdbmadmax', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Madagascar', 'movies2&url=tmdbmadagascar', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Major League', 'movies2&url=tmdbmajor', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Maze Runner', 'movies2&url=tmdbmaze', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Meet The Parents', 'movies2&url=tmdbmeet', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Men in Black', 'movies2&url=tmdbmib', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Mission Impossible', 'movies2&url=tmdbmission', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Monsters INC', 'movies2&url=tmdbmonster', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Monty Python', 'movies2&url=tmdbmonty', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Mulan', 'movies2&url=tmdbmulan', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('My Big Fat Greek Wedding', 'movies2&url=tmdbmbfgw', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('National Treasure', 'movies2&url=tmdbnational', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Never Back Down', 'movies2&url=tmdbnever', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('New Groove', 'movies2&url=tmdbnewgroove', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Night At The Museum', 'movies2&url=tmdbnatm', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Nims Island', 'movies2&url=tmdbnims', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Ninja', 'movies2&url=tmdbninja', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Now You See Me', 'movies2&url=tmdbnysm', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Nymphomaniac', 'movies2&url=tmdbnymph', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Oceans', 'movies2&url=tmdboceans', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Olympus Has Fallen', 'movies2&url=tmdbolympus', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Once Were Warriors', 'movies2&url=tmdbonce', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Ong Bak', 'movies2&url=tmdbong', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Open Season', 'movies2&url=tmdbopen', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Paranormal Activity', 'movies2&url=tmdbparanormal', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Percy Jackson', 'movies2&url=tmdbpercy', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Peter Pan', 'movies2&url=tmdbpeter', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Pirates of The Caribbean', 'movies2&url=tmdbpirates', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Pitch Perfect', 'movies2&url=tmdbpitch', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Planes', 'movies2&url=tmdbplanes', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Planet of The Apes', 'movies2&url=tmdbplanet', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Pocahontas', 'movies2&url=tmdbpoca', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Police Academy', 'movies2&url=tmdbpolice', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Poltergeist', 'movies2&url=tmdbpolter', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Power Rangers', 'movies2&url=tmdbpowerrangers', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Predator', 'movies2&url=tmdbpredator', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Problem Child', 'movies2&url=tmdbproblem', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Psycho', 'movies2&url=tmdbpsycho', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Quarantine', 'movies2&url=tmdbquarantine', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('R.E.D.', 'movies2&url=tmdbred', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Rambo', 'movies2&url=tmdbrambo', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Red Cliff', 'movies2&url=tmdbredcliff', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Resident Evil', 'movies2&url=tmdbresident', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Riddick', 'movies2&url=tmdbriddick', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Ride Along', 'movies2&url=tmdbride', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Rio', 'movies2&url=tmdbrio', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Rise of the Footsoldier', 'movies2&url=tmdbrise', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Robocop', 'movies2&url=tmdbrobocop', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Rocky', 'movies2&url=tmdbrocky', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Romancing The Stone', 'movies2&url=tmdbromancing', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Rush Hour', 'movies2&url=tmdbrush', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Sammys Adventures', 'movies2&url=tmdbsammy', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Saw', 'movies2&url=tmdbsaw', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Scary Movie', 'movies2&url=tmdbscary', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Scream', 'movies2&url=tmdbscream', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Shanghai', 'movies2&url=tmdbshanghai', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Sherlock Holmes', 'movies2&url=tmdbsherlock', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Short Circuit', 'movies2&url=tmdbshort', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Shrek', 'movies2&url=tmdbshrek', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Sin City', 'movies2&url=tmdbsin', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Smokey and The Bandit', 'movies2&url=tmdbsmokey', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Space Chimps', 'movies2&url=tmdbspacechimps', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('SpongBob Squarepants', 'movies2&url=tmdbspongebob', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Spy Kids', 'movies2&url=tmdbspy', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Star Trek', 'movies2&url=tmdbstartrek', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Star Wars', 'movies2&url=tmdbstarwars', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Starship Troopers', 'movies2&url=tmdbstarship', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Step Up', 'movies2&url=tmdbstepup', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Stuart Little', 'movies2&url=tmdbstuart', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Taken', 'movies2&url=tmdbtaken', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Tarzan', 'movies2&url=tmdbtarzan', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Ted', 'movies2&url=tmdbted', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Teen Wolf', 'movies2&url=tmdbteen', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Teenage Mutant Ninja Turtles', 'movies2&url=tmdbteenage', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Terminator', 'movies2&url=tmdbterminator', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Texas Chainsaw Massacre', 'movies2&url=tmdbtexas', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Before', 'movies2&url=tmdbbefore', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Best Exotic Marigold Hotel', 'movies2&url=tmdbbestexotic', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Butterfly Effect', 'movies2&url=tmdbbutterfly', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Chronicles of Narnia', 'movies2&url=tmdbnarnia', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Conjuring', 'movies2&url=tmdbconjuring', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Crow', 'movies2&url=tmdbcrow', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Expendables', 'movies2&url=tmdbexpendables', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Flintstones', 'movies2&url=tmdbflintstones', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Fly', 'movies2&url=tmdbfly', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Godfather', 'movies2&url=tmdbgodfather', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Grudge', 'movies2&url=tmdbgrudge', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Hangover', 'movies2&url=tmdbhangover', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Hills Have Eyes', 'movies2&url=tmdbhills', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Hobbit', 'movies2&url=tmdbhobbit', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Human Centipede', 'movies2&url=tmdbhuman', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Huntsman', 'movies2&url=tmdbhuntsman', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Inbetweeners', 'movies2&url=tmdbinbetweeners', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Jungle Book', 'movies2&url=tmdbjungle', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Karate Kid', 'movies2&url=tmdbkarate', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Land Before Time', 'movies2&url=tmdblbt', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Lion King', 'movies2&url=tmdblion', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Little Mermaid', 'movies2&url=tmdbmermaid', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Man With No Name', 'movies2&url=tmdbnoman', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Matrix', 'movies2&url=tmdbmatrix', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Mechanic', 'movies2&url=tmdbmechanic', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Mighty Ducks', 'movies2&url=tmdbmighty', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Mummy', 'movies2&url=tmdbmummy', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Muppets', 'movies2&url=tmdbmuppets', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Naked Gun', 'movies2&url=tmdbnaked', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Never Ending Story', 'movies2&url=tmdbnes', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Nightmare On Elm Street', 'movies2&url=tmdbnightmare', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Omen', 'movies2&url=tmdbomen', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Pink Panther', 'movies2&url=tmdbpink', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Protector', 'movies2&url=tmdbprotector', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Punisher', 'movies2&url=tmdbpunisher', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Purge', 'movies2&url=tmdbpurge', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Raid', 'movies2&url=tmdbraid', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Reef', 'movies2&url=tmdbreef', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Ring', 'movies2&url=tmdbring', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Sandlot', 'movies2&url=tmdbsandlot', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Smurfs', 'movies2&url=tmdbsmurfs', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Tooth Fairy', 'movies2&url=tmdbtooth', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Whole Nine Yards', 'movies2&url=tmdbwholenine', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('The Woman in Black', 'movies2&url=tmdbwoman', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Think Like a Man', 'movies2&url=tmdbthink', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Thomas & Friends', 'movies2&url=tmdbthomas', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Three Colors', 'movies2&url=tmdbthree', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Tinker Bell', 'movies2&url=tmdbtinker', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Titans', 'movies2&url=tmdbtitans', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Toy Story', 'movies2&url=tmdbtoy', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Transformers', 'movies2&url=tmdbtransformers', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Transporter', 'movies2&url=tmdbtransporter', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Tremors', 'movies2&url=tmdbtremors', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Tron', 'movies2&url=tmdbtron', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Twilight', 'movies2&url=tmdbtwilight', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Under Siege', 'movies2&url=tmdbunder', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Underworld', 'movies2&url=tmdbunderworld', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Undisputed', 'movies2&url=tmdbundisputed', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Universal Soldier', 'movies2&url=tmdbuniversal', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('VHS', 'movies2&url=tmdbvhs', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Wallace & Gromit', 'movies2&url=tmdbwallace', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Waynes World', 'movies2&url=tmdbwayne', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Weekend at Bernies', 'movies2&url=tmdbweekend', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Wrong Turn', 'movies2&url=tmdbwrong', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('xXx', 'movies2&url=tmdbxxx', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Young Guns', 'movies2&url=tmdbyoung', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Zoolander', 'movies2&url=tmdbzoo', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Zorro', 'movies2&url=tmdbzorro', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.endDirectory()
        
        
    def myclassics(self, lite=False):
        control.infoDialog(control.lang(101011).encode('utf-8'), sound=True, icon='INFO')
        self.addDirectoryItem('Action', 'movies2&url=tmdbclaction', 'tmdb.png', 'DefaultVideoPlaylists.png')
        #self.addDirectoryItem('Adventure', 'movies2&url=tmdbcladven', 'tmdb.png', 'DefaultVideoPlaylists.png')
        #self.addDirectoryItem('Animation', 'movies2&url=tmdbclanim', 'tmdb.png', 'DefaultVideoPlaylists.png')
        #self.addDirectoryItem('Comedy', 'movies2&url=tmdbclcom', 'tmdb.png', 'DefaultVideoPlaylists.png')
        #self.addDirectoryItem('Crime', 'movies2&url=tmdbclcrime', 'tmdb.png', 'DefaultVideoPlaylists.png')
        #self.addDirectoryItem('Drama', 'movies2&url=tmdbcldram', 'tmdb.png', 'DefaultVideoPlaylists.png')
        #self.addDirectoryItem('Family', 'movies2&url=tmdbclfam', 'tmdb.png', 'DefaultVideoPlaylists.png')
        #self.addDirectoryItem('Fantasy', 'movies2&url=tmdbfancl', 'tmdb.png', 'DefaultVideoPlaylists.png')
        #self.addDirectoryItem('Horror', 'movies2&url=tmdbclhoro', 'tmdb.png', 'DefaultVideoPlaylists.png')
        #self.addDirectoryItem('Mystery', 'movies2&url=tmdbclmys', 'tmdb.png', 'DefaultVideoPlaylists.png')
        #self.addDirectoryItem('Romance', 'movies2&url=tmdbclrom', 'tmdb.png', 'DefaultVideoPlaylists.png')
        #self.addDirectoryItem('SciFi', 'movies2&url=tmdbclscifi', 'tmdb.png', 'DefaultVideoPlaylists.png')
        #self.addDirectoryItem('Thriller', 'movies2&url=tmdbclthrill', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Westerns', 'movies2&url=tmdbwesterns2', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.endDirectory()
        
        
    def mymore(self, lite=False):
        self.addDirectoryItem('Diddy Kong Favs', 'movies2&url=tmdbkatsfavs', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Dixie Kong Movies', 'movies2&url=tmdbwarm', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Donkey Kong', 'movies2&url=tmdbldmov', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Cranky Kong Favs', 'movies2&url=tmdbBcfavs', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Candy Kong Favs', 'movies2&url=tmdbenforcersfavs', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Stalker Favs', 'movies2&url=tmdbstalkerfav', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Horror Icons 2', 'movies2&url=tmdbHorroricons', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('MorbidlyHorrorfying', 'movies2&url=tmdbMh', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Canada Loves', 'movies2&url=tmdbcanada', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Paranormal', 'movies2&url=tmdbparanormal', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Anime', 'movies2&url=tmdbanime', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Sci Fi', 'movies2&url=tmdbScfinew', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Krests', 'movies2&url=tmdbkrests', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Leons Creations', 'movies2&url=tmdbleon', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Comedy', 'movies2&url=tmdbcom1', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Christmas Movies', 'movies2&url=tmdbxmas', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Super Heroes Section', 'movies2&url=tmdbsuper', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Crusher sr', 'movies2&url=tmdbCrushersr', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Toddlers', 'movies2&url=tmdbtoddler', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Learning and Nature', 'movies2&url=tmdblearning', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Teen', 'movies2&url=tmdbteen', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Kids Zone', 'movies2&url=tmdbKids', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Addiction', 'movies2&url=tmdbaddiction', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Biographies', 'movies2&url=tmdbdbiographies', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Other Mysteries', 'movies2&url=tmdbother', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Myths', 'movies2&url=tmdbmyths', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Urban', 'movies2&url=tmdburban', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Mental Health', 'movies2&url=tmdbmental', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Killers', 'movies2&url=tmdbkillers', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.addDirectoryItem('Conspiracies', 'movies2&url=tmdbConspiracies', 'tmdb.png', 'DefaultVideoPlaylists.png')
        self.endDirectory()
        
        
    def downloads(self):
        movie_downloads = control.setting('movie.download.path')
        if len(control.listDir(movie_downloads)[0]) > 0:
            self.addDirectoryItem(32001, movie_downloads, 'movies.png', 'DefaultVideoPlaylists.png', isAction=False)
        self.endDirectory()
        
        
    def views(self):
        try:
            control.idle()
            items = [ (control.lang(32001).encode('utf-8'), 'movies'), (control.lang(32002).encode('utf-8'), 'tvshows'), (control.lang(32054).encode('utf-8'), 'seasons'), (control.lang(32038).encode('utf-8'), 'episodes') ]
            select = control.selectDialog([i[0] for i in items], control.lang(32049).encode('utf-8'))
            if select == -1: return
            content = items[select][1]
            title = control.lang(32059).encode('utf-8')
            url = '%s?action=addView&content=%s' % (sys.argv[0], content)
            poster, banner, fanart = control.addonPoster(), control.addonBanner(), control.addonFanart()
            item = control.item(label=title)
            item.setInfo(type='Video', infoLabels = {'title': title})
            item.setArt({'icon': poster, 'thumb': poster, 'poster': poster, 'tvshow.poster': poster, 'season.poster': poster, 'banner': banner, 'tvshow.banner': banner, 'season.banner': banner})
            item.setProperty('Fanart_Image', fanart)
            control.addItem(handle=int(sys.argv[1]), url=url, listitem=item, isFolder=False)
            control.content(int(sys.argv[1]), content)
            control.directory(int(sys.argv[1]), cacheToDisc=True)
            from resources.lib.modules import cache
            views.setView(content, {})
        except:
            return


    def accountCheck(self):
        if traktCredentials == False and imdbCredentials == False:
            control.idle()
            control.infoDialog(control.lang(32042).encode('utf-8'), sound=True, icon='WARNING')
            sys.exit()


    def clearCache(self):
        control.idle()
        yes = control.yesnoDialog(control.lang(32056).encode('utf-8'), '', '')
        if not yes: return
        from resources.lib.modules import cache
        cache.clear()
        control.infoDialog(control.lang(32057).encode('utf-8'), sound=True, icon='INFO')


    def addDirectoryItem(self, name, query, thumb, icon, queue=False, isAction=True, isFolder=True):
        try: name = control.lang(name).encode('utf-8')
        except: pass
        url = '%s?action=%s' % (sysaddon, query) if isAction == True else query
        thumb = os.path.join(artPath, thumb) if not artPath == None else icon
        cm = []
        if queue == True: cm.append((queueMenu, 'RunPlugin(%s?action=queueItem)' % sysaddon))
        item = control.item(label=name)
        item.addContextMenuItems(cm)
        item.setArt({'icon': thumb, 'thumb': thumb})
        if not addonFanart == None: item.setProperty('Fanart_Image', addonFanart)
        control.addItem(handle=syshandle, url=url, listitem=item, isFolder=isFolder)


    def endDirectory(self):
        control.directory(syshandle, cacheToDisc=True)

